server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 3629603700-4p2ga9q7dov6m4luhb91bjia3if5a05f.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile