server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 3629603700-4p2ga9q7dov6m4luhb91bjia3if5a05f.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 341458270893837
            client-secret: 42379a4815c1917ba156d195847c86cd
            scope:
              - email
              - public_profile


          naver:
            client-id: f6oJqWXOvlQKBrMxnIR3
            client-secret: 2jCstfJEIp
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
